[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "=1.14.26"

[[constraint]]
  name = "github.com/kylelemons/godebug"
  revision = "a616ab194758ae0a11290d87ca46ee8c440117b0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sync"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"
